### PR TITLE
fix: pump link

### LINKED ISSUE #873: Reintroduce Link to OSM water well editor
We added a link to a MapComplete Water Well Editor in https://github.com/technologiestiftung/giessdenkiez-de/issues/460 and I am surprised to see that it was removed. 
> image
[Source](https://www.giessdenkiez.de/map?lat=52.472420675160805&lng=13.446626085788125&zoom=20&treeAge=young&treeAge=medium&treeAge=old&isPumpsVisible=true)

To be honest, I am even more surprised that it was removed without any ping to me / the Berlin OSM Community about it. We have been promoting the app as a great example of collaborative data editing with OSM… which apparently it not true anymore.

With the start of the new season of public water well checking I updated the MapComplete theme this week to get it working with the latest MapComplete version. It is now hosted on MapComplete infrastructure at https://mapcomplete.org/theme.html?lat=52.47271334046087&lon=13.445970188175806&userlayout=https%3A%2F%2Fstudio.mapcomplete.org%2F11881%2Fthemes%2Fberlin_emergency_water_pumps%2Fberlin_emergency_water_pumps.json

Are you open to adding the link back to the dialogue?
Is that something you can add or would you prefer a PR from us?

### PR DESCRIPTION
**Pull request by Jaszkowic**
closes #873

### CODE REVIEW

File: src/i18n/de.ts [hunk 1]
```diff
@@ -453,6 +453,9 @@ Insbesondere junge Bäume brauchen in den ersten Jahren Wasser. Lieber seltener,
 		status: "Status",
 		lastCheck: "Letzter Check",
 		update: "Status in OpenStreetMap aktualisieren",
+		updateLink: (id: number, lat: number, lng: number) => {
+			return `https://mapcomplete.org/theme.html?z=15.1&lat=${lat}&lon=${lng}&userlayout=https%3A%2F%2Fstudio.mapcomplete.org%2F11881%2Fthemes%2Fberlin_emergency_water_pumps%2Fberlin_emergency_water_pumps.json#node/${id}`;
```
Comment (ff6347) [inline src/i18n/de.ts:457]: Could the URL be stored in one location or be a function that returns the updated link so we don't have to maintain the URL in two locations?

**Review by ff6347 — CHANGES_REQUESTED** [review]

File: src/i18n/de.ts (hunk 1 above)
Comment (Jaszkowic) [reply src/i18n/de.ts]: fixed in latest commit

**Review by ff6347 — APPROVED** [review]
❤️ it
